### ISSUE TITLE
PolygraphyException: Could not deserialize engine. 

### ISSUE THREAD

**Issue by osuta1010** [chavinlo/sda-node#10]
I here a error when i run `LD_PRELOAD=${PLUGIN_LIBS} gunicorn -w 1 -b 0.0.0.0:5000 main:app`
` LD_PRELOAD=${PLUGIN_LIBS} gunicorn -w 1 -b 0.0.0.0:5000 main:app
[2023-02-06 12:45:00 +0000] [9858] [INFO] Starting gunicorn 20.1.0
[2023-02-06 12:45:00 +0000] [9858] [INFO] Listening at: http://0.0.0.0:5000 (9858)
[2023-02-06 12:45:00 +0000] [9858] [INFO] Using worker: sync
[2023-02-06 12:45:00 +0000] [9860] [INFO] Booting worker with pid: 9860
Downloading (…)ain/model_index.json:   0%|                                                               | 0.00/407 [00:00<?, ?B/sDownloading (…)ain/model_index.json: 100%|????????????????????????????????????????????????????????| 407/407 [00:00<00:00, 97.2kB/s]
{'_class_name': 'StableDiffusionAccelerated_Base', '_sda_version': '0.1.2', '_trt_version': '8.5.1', '_cuda_version': '11.6', '_cudnn_version': '7.5', '_onnx2trt_version': '8.5.1', 'unet': {'precision': 'fp16', 'path': 'engine/unet.plan'}, 'clip': {'path': 'engine/clip.plan'}, 'de_vae': {'path': 'engine/de_vae.plan'}}
['hf', 'tensorrt/anything-v3']
Downloading (…)"clip.plan";:   0%|                                                                      | 0.00/250M [00:00<?, ?B/sDownloading (…)"clip.plan";:  13%|????????                                                     | 31.5M/250M [00:00<00:02, 90.1MB/sDownloading (…)"clip.plan";:  17%|???????????                                                  | 41.9M/250M [00:00<00:02, 93.1MB/sDownloading (…)"clip.plan";:  25%|????????????????                                             | 62.9M/250M [00:00<00:03, 61.1MB/sDownloading (…)"clip.plan";:  38%|???????????????????????                                      | 94.4M/250M [00:01<00:02, 69.0MB/sDownloading (…)"clip.plan";:  46%|?????????????????????????????                                 | 115M/250M [00:01<00:02, 65.1MB/sDownloading (…)"clip.plan";:  59%|?????????????????????????????????????                         | 147M/250M [00:02<00:01, 71.8MB/sDownloading (…)"clip.plan";:  71%|?????????????????????????????????????????????                 | 178M/250M [00:02<00:01, 61.7MB/sDownloading (…)"clip.plan";:  80%|??????????????????????????????????????????????????            | 199M/250M [00:03<00:00, 62.8MB/sDownloading (…)"clip.plan";:  92%|??????????????????????????????????????????????????????????    | 231M/250M [00:03<00:00, 70.6MB/sDownloading (…)"clip.plan";:  96%|????????????????????????????????????????????????????????????  | 241M/250M [00:03<00:00, 69.1MB/sDownloading (…)"clip.plan";: 100%|??????????????????????????????????????????????????????????????| 250M/250M [00:03<00:00, 70.1MB/s]
Loading TensorRT engine: /root/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
[I] Loading bytes from /root/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
[E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 237, Serialized Engine Version: 232)
[E] 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
[!] Could not deserialize engine. See log for details.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/sda-node/threads/base.py", line 62, in image_generator
    indiv_engine.activate() #<----
  File "/workspace/sda-node/threads/trt/utilities.py", line 89, in activate
    self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
  File "<string>", line 3, in func_impl
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 564, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/logger/logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.`

Error in docker running TensorRT/demo/Diffusion/demo-diffusion.py.
Thank you.

**Comment by 78Alpha** [comment]
This happens when the model you are running does not match your GPU. Each TRT model made is GPU specific. If it was compiled on a 4090, it can only be run on a 4090 with that specific version of TRT (8.6.0 or another).
