### ISSUE TITLE
How can I convert other models 

### ISSUE THREAD

**Issue by camenduru** [chavinlo/sda-node#5]
Hi @chavinlo 👋 thanks for the repo ❤ how can I convert ckpt models to .plan like this one https://huggingface.co/tensorrt/Anything-V3/tree/main/engine

**Comment by chavinlo** [comment]
I will upload it to the repo soon.
In the meantime just grab this file: https://gist.github.com/chavinlo/7203d4cca8b5894f038c4a5cca4ef093
and place it in sda-node

**Comment by chavinlo** [comment]
Also, you might want to compile Nvidia's OSS plugin with the following command:
cmake .. -DTRT_OUT_DIR=$PWD/out -DCUDA_VERSION=11.6 -DCUDNN_VERSION=7.5
this is to support older versions.

**Comment by camenduru** [comment]
thanks @chavinlo ❤

**Comment by camenduru** [comment]
Hi @chavinlo 👋 I tried running compiler.py and I got this error
```py
gjt7g:/content/sda-node$ export TF_ENABLE_ONEDNN_OPTS=0 && python compiler.py -m ckpt/anything-v3.0 -o /content/av3.0 -v
THE FOLLOWING VERSIONS WERE EXTRACTED FROM THE CMAKECACHE USED TO BUILD THE GIVEN PLUGIN.
Detected TensorRT version: 8.5.2
Detected ONNX2TRT version: 8.5.2
Using model: ckpt/anything-v3.0
Exception ignored in: <function Engine.__del__ at 0x7f5ef12c2af0>
Traceback (most recent call last):
  File "/content/sda-node/threads/trt/utilities.py", line 61, in __del__
    [buf.free() for buf in self.buffers.values() if isinstance(buf, cuda.DeviceArray) ]
AttributeError: 'Engine' object has no attribute 'buffers'
Traceback (most recent call last):
  File "compiler.py", line 167, in <module>
    engine = Engine(model_name, engine_dir)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by camenduru** [comment]
models in https://huggingface.co/tensorrt not working for me 😐 I think I should compile the models with same machine with compiler.py right? I will try fix the compiler.py error I got

```py
[E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 237, Serialized Engine Version: 232)
```

```py
[2023-01-31 17:57:07 +0000] [83] [INFO] Starting gunicorn 20.1.0
[2023-01-31 17:57:07 +0000] [83] [INFO] Listening at: http://0.0.0.0:7860 (83)
[2023-01-31 17:57:07 +0000] [83] [INFO] Using worker: sync
[2023-01-31 17:57:07 +0000] [85] [INFO] Booting worker with pid: 85
2023-01-31 17:57:10.983207: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Downloading (…)ain/model_index.json:   0%|          | 0.00/407 [00:00<?, ?B/s]
Downloading (…)ain/model_index.json: 100%|██████████| 407/407 [00:00<00:00, 57.5kB/s]
{'_class_name': 'StableDiffusionAccelerated_Base', '_sda_version': '0.1.2', '_trt_version': '8.5.1', '_cuda_version': '11.6', '_cudnn_version': '7.5', '_onnx2trt_version': '8.5.1', 'unet': {'precision': 'fp16', 'path': 'engine/unet.plan'}, 'clip': {'path': 'engine/clip.plan'}, 'de_vae': {'path': 'engine/de_vae.plan'}}
['hf', 'tensorrt/anything-v3']

Downloading (…)22%3B&x-id=GetObject:   0%|          | 0.00/250M [00:00<?, ?B/s]
Downloading (…)22%3B&x-id=GetObject:   8%|▊         | 21.0M/250M [00:00<00:01, 191MB/s]
Downloading (…)22%3B&x-id=GetObject:  17%|█▋        | 41.9M/250M [00:00<00:02, 79.5MB/s]
Downloading (…)22%3B&x-id=GetObject:  25%|██▌       | 62.9M/250M [00:00<00:02, 67.1MB/s]
Downloading (…)22%3B&x-id=GetObject:  38%|███▊      | 94.4M/250M [00:01<00:02, 62.9MB/s]
Downloading (…)22%3B&x-id=GetObject:  46%|████▌     | 115M/250M [00:01<00:02, 63.6MB/s] 
Downloading (…)22%3B&x-id=GetObject:  59%|█████▊    | 147M/250M [00:02<00:01, 73.8MB/s]
Downloading (…)22%3B&x-id=GetObject:  71%|███████▏  | 178M/250M [00:02<00:00, 72.4MB/s]
Downloading (…)22%3B&x-id=GetObject:  80%|███████▉  | 199M/250M [00:02<00:00, 63.3MB/s]
Downloading (…)22%3B&x-id=GetObject:  92%|█████████▏| 231M/250M [00:03<00:00, 63.1MB/s]
Downloading (…)22%3B&x-id=GetObject: 100%|██████████| 250M/250M [00:03<00:00, 71.6MB/s]
[!] Could not deserialize engine. See log for details.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/content/sda-node/threads/base.py", line 62, in image_generator
    indiv_engine.activate() #<----
  File "/content/sda-node/threads/trt/utilities.py", line 89, in activate
    self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
  File "<string>", line 3, in func_impl
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
    return self.call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 564, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "/usr/local/lib/python3.8/dist-packages/polygraphy/logger/logger.py", line 597, in critical
    raise PolygraphyException(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.
[2023-01-31 18:29:49 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:85)
[2023-01-31 18:29:49 +0000] [85] [INFO] Worker exiting (pid: 85)
Loading TensorRT engine: /home/user/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
[I] Loading bytes from /home/user/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
[E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 237, Serialized Engine Version: 232)
[E] 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
front req {'prompt': '(Masterpiece:1.2), best quality, illustration, (delicate details:1.5),extremely detailed CG, lovely layered white hair, absurdly long hair, (glowing blue eyes), lip gloss, makeup, (school:1.5), evil smile, medium breasts, school girl, ((arms behind back)), school uniform', 'negprompt': 'nsfw, (worst quality, low quality:1.3), (depth of field, blurry:1.2), (greyscale, monochrome:1.1), 3D face, nose, cropped, lowres, text, jpeg artifacts, signature, watermark, username, blurry, artist name, trademark, watermark, title', 'width': 512, 'height': 512, 'steps': 25, 'cfg': 7, 'seed': 86, 'scheduler': 'LMSD', 'mode': 'file', 'lpw': True}
[2023-01-31 18:29:50 +0000] [83] [WARNING] Worker with pid 85 was terminated due to signal 9
[2023-01-31 18:29:50 +0000] [96] [INFO] Booting worker with pid: 96
```

**Comment by camenduru** [comment]
solved 🎉

**Comment by chavinlo** [comment]
> models in https://huggingface.co/tensorrt not working for me 😐 I think I should compile the models with same machine with compiler.py right? I will try fix the compiler.py error I got
> 
> ```python
> [E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 237, Serialized Engine Version: 232)
> ```
> 
> ```python
> [2023-01-31 17:57:07 +0000] [83] [INFO] Starting gunicorn 20.1.0
> [2023-01-31 17:57:07 +0000] [83] [INFO] Listening at: http://0.0.0.0:7860 (83)
> [2023-01-31 17:57:07 +0000] [83] [INFO] Using worker: sync
> [2023-01-31 17:57:07 +0000] [85] [INFO] Booting worker with pid: 85
> 2023-01-31 17:57:10.983207: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
> 
> Downloading (…)ain/model_index.json:   0%|          | 0.00/407 [00:00<?, ?B/s]
> Downloading (…)ain/model_index.json: 100%|██████████| 407/407 [00:00<00:00, 57.5kB/s]
> {'_class_name': 'StableDiffusionAccelerated_Base', '_sda_version': '0.1.2', '_trt_version': '8.5.1', '_cuda_version': '11.6', '_cudnn_version': '7.5', '_onnx2trt_version': '8.5.1', 'unet': {'precision': 'fp16', 'path': 'engine/unet.plan'}, 'clip': {'path': 'engine/clip.plan'}, 'de_vae': {'path': 'engine/de_vae.plan'}}
> ['hf', 'tensorrt/anything-v3']
> 
> Downloading (…)22%3B&x-id=GetObject:   0%|          | 0.00/250M [00:00<?, ?B/s]
> Downloading (…)22%3B&x-id=GetObject:   8%|▊         | 21.0M/250M [00:00<00:01, 191MB/s]
> Downloading (…)22%3B&x-id=GetObject:  17%|█▋        | 41.9M/250M [00:00<00:02, 79.5MB/s]
> Downloading (…)22%3B&x-id=GetObject:  25%|██▌       | 62.9M/250M [00:00<00:02, 67.1MB/s]
> Downloading (…)22%3B&x-id=GetObject:  38%|███▊      | 94.4M/250M [00:01<00:02, 62.9MB/s]
> Downloading (…)22%3B&x-id=GetObject:  46%|████▌     | 115M/250M [00:01<00:02, 63.6MB/s] 
> Downloading (…)22%3B&x-id=GetObject:  59%|█████▊    | 147M/250M [00:02<00:01, 73.8MB/s]
> Downloading (…)22%3B&x-id=GetObject:  71%|███████▏  | 178M/250M [00:02<00:00, 72.4MB/s]
> Downloading (…)22%3B&x-id=GetObject:  80%|███████▉  | 199M/250M [00:02<00:00, 63.3MB/s]
> Downloading (…)22%3B&x-id=GetObject:  92%|█████████▏| 231M/250M [00:03<00:00, 63.1MB/s]
> Downloading (…)22%3B&x-id=GetObject: 100%|██████████| 250M/250M [00:03<00:00, 71.6MB/s]
> [!] Could not deserialize engine. See log for details.
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/content/sda-node/threads/base.py", line 62, in image_generator
>     indiv_engine.activate() #<----
>   File "/content/sda-node/threads/trt/utilities.py", line 89, in activate
>     self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
>   File "<string>", line 3, in func_impl
>   File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/base/loader.py", line 42, in __call__
>     return self.call_impl(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/polygraphy/backend/trt/loader.py", line 564, in call_impl
>     G_LOGGER.critical("Could not deserialize engine. See log for details.")
>   File "/usr/local/lib/python3.8/dist-packages/polygraphy/logger/logger.py", line 597, in critical
>     raise PolygraphyException(message) from None
> polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.
> [2023-01-31 18:29:49 +0000] [83] [CRITICAL] WORKER TIMEOUT (pid:85)
> [2023-01-31 18:29:49 +0000] [85] [INFO] Worker exiting (pid: 85)
> Loading TensorRT engine: /home/user/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
> [I] Loading bytes from /home/user/.cache/huggingface/hub/models--tensorrt--anything-v3/snapshots/e6051a5d7720f15b4393a9be0c031fb5dc7031ef/engine/clip.plan
> [E] 1: [stdArchiveReader.cpp::StdArchiveReader::42] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 237, Serialized Engine Version: 232)
> [E] 4: [runtime.cpp::deserializeCudaEngine::66] Error Code 4: Internal Error (Engine deserialization failed.)
> front req {'prompt': '(Masterpiece:1.2), best quality, illustration, (delicate details:1.5),extremely detailed CG, lovely layered white hair, absurdly long hair, (glowing blue eyes), lip gloss, makeup, (school:1.5), evil smile, medium breasts, school girl, ((arms behind back)), school uniform', 'negprompt': 'nsfw, (worst quality, low quality:1.3), (depth of field, blurry:1.2), (greyscale, monochrome:1.1), 3D face, nose, cropped, lowres, text, jpeg artifacts, signature, watermark, username, blurry, artist name, trademark, watermark, title', 'width': 512, 'height': 512, 'steps': 25, 'cfg': 7, 'seed': 86, 'scheduler': 'LMSD', 'mode': 'file', 'lpw': True}
> [2023-01-31 18:29:50 +0000] [83] [WARNING] Worker with pid 85 was terminated due to signal 9
> [2023-01-31 18:29:50 +0000] [96] [INFO] Booting worker with pid: 96
> ```

Yeah, turns out my methodology wasn't right. It is not possible to compile a model and use it on another gpu that's not the same type (RTX3090 != A100)

**Comment by camenduru** [comment]
I used the main repo for compiling the model https://twitter.com/camenduru/status/1620904348321738752 I think also same model works with your code I will try tomorrow thanks ❤
